export const COLONICS_CONDITIONS = [
  'Diabetes',
  'Hypertension',
  'Tumor (Cyst/Bukol)',
  'Uric Acid/Gout',
  'Urinary Problem',
  'Insomnia',
  'Overweight',
  'Tuberculosis',
  'Goiter',
  'Allergy',
  'Liver Cirrhosis',
  'Cancer',
  'Parasite (Bulate)',
  'Ulcer',
  'Sinusitis',
  'Paralysis',
  'Kabag (Bloating)',
  'Heart Disease',
  'Arthritis/Gout',
  'Migraine',
  'Back Pains',
  'Skin Disease',
  'Asthma',
  'Sexual Problems',
  'Prostate Problem',
  'Intestinal Problem',
] as const
